#!/bin/bash
echo "=== Testing Fixes ==="
echo ""

echo "1. Checking for syntax errors..."
echo "   - page-stabilizer.js:"
node -c js/page-stabilizer.js && echo "     ✅ OK" || echo "     ❌ Syntax error"
echo "   - whisper-loader.js:"
node -c js/whisper-loader.js && echo "     ✅ OK" || echo "     ❌ Syntax error"
echo "   - whisper-dashboard.js:"
node -c js/whisper-dashboard.js && echo "     ✅ OK" || echo "     ❌ Syntax error"

echo ""
echo "2. Checking file existence..."
[ -f "index.html" ] && echo "   ✅ index.html exists" || echo "   ❌ index.html missing"
[ -f "css/dynamic-styles.css" ] && echo "   ✅ CSS exists" || echo "   ❌ CSS missing"
[ -f "js/whisper-loader.js" ] && echo "   ✅ whisper-loader.js exists" || echo "   ❌ whisper-loader.js missing"
[ -f "whisper-dashboard.html" ] && echo "   ✅ whisper-dashboard.html exists" || echo "   ❌ whisper-dashboard.html missing"

echo ""
echo "3. Checking for common issues..."
grep -q "Unexpected token" js/whisper-loader.js && echo "   ⚠️  Found 'Unexpected token' in whisper-loader.js" || echo "   ✅ No unexpected tokens"
grep -q "SyntaxError" js/whisper-loader.js && echo "   ⚠️  Found 'SyntaxError' in whisper-loader.js" || echo "   ✅ No syntax errors mentioned"

echo ""
echo "=== Test Complete ==="
echo ""
echo "To start the server:"
echo "cd ~/liveones && python3 -m http.server 8000"
echo ""
echo "Then open: http://localhost:8000"
echo ""
echo "To create a test whisper, open:"
echo "http://localhost:8000/test-whisper.html"
