#!/bin/bash
echo "Testing Firestore permissions fix..."
echo "1. Make sure you've updated Firestore rules in Firebase Console"
echo "2. Rules should allow public read access to users collection"
echo ""
echo "To update rules:"
echo "1. Go to https://console.firebase.google.com/"
echo "2. Select your project: whisper-chat-live"
echo "3. Go to Firestore Database → Rules tab"
echo "4. Paste the rules from firestore-rules.md"
echo "5. Click 'Publish'"
echo ""
echo "Testing redirect fix..."
echo "The new logic:"
echo "- Only redirects if user JUST logged in (not on page refresh)"
echo "- Uses sessionStorage to track login state"
echo "- Prevents multiple redirects with 'redirecting' flag"
echo ""
echo "Test steps:"
echo "1. Log out completely (clear sessionStorage too)"
echo "2. Go to index.html"
echo "3. Log in - should redirect to dashboard after 1.5 seconds"
echo "4. Refresh dashboard - should NOT redirect"
echo "5. Go back to index.html - should NOT redirect"
echo "6. Log out - should redirect to index.html"
